style = "blue"

always_use_return = false
annotate_untyped_fields_with_any = true
import_to_using = false
indent = 2
short_to_long_function_def = false
always_for_in = true
join_lines_based_on_source = true
margin = 88
remove_extra_newlines = true
format_docstrings = true
long_to_short_function_def = true