name = "HodgeDiamonds"
uuid = "b8a89795-2f98-425e-8b2b-335edb314b36"
authors = ["Pieter Belmans <pieterbelmans@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
