name = "HodgeDiamonds"
uuid = "b8a89795-2f98-425e-8b2b-335edb314b36"
authors = ["Pieter Belmans <pieterbelmans@gmail.com> and contributors"]
version = "0.0.1-DEV"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
AbstractAlgebra = "0.44.2"
PrettyTables = "2.4.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
